### ISSUE TITLE
anyxml.Xml does not handle nil attribute values correctly

### ISSUE THREAD

**Issue by dechamps** [clbanning/anyxml#3]
Steps to reproduce:

```go
package main
  
import (
        "fmt"
        "github.com/clbanning/anyxml"
)

func main() {
        xmlout, err := anyxml.Xml(map[string]interface{}{"toplevel": nil}, "root")
        if err != nil {
                return
        }
        fmt.Println(string(xmlout))
}
```

Expected result:

```xml
<root><toplevel /></root>
```

Actual result:

```xml
<root><toplevel</root>
```

Which is not valid XML.

This is causing downstream issue chrismalek/jsontoxml-cli#1.

**Comment by clbanning** [comment]
Don't know what you weren't using clbanning/j2x or clbanning/mxj/j2x instead of chrismalek/jsontoxml

**Comment by dechamps** [comment]
Well that would be a question for @chrismalek, jsontoxml-cli's author.

That said, I found it was very easy to migrate jsontoxml-cli to mxj, so I sent chrismalek/jsontoxml-cli#2 to do just that.

Thanks for the help. It would probably be a good idea to update your repo to reflect the fact that it should not be used, and direct users to clbanning/mxj.
