### ISSUE TITLE
Nested object support

### ISSUE THREAD

**Issue by wz2b** [clbanning/anyxml#6]
Should this work?

```
type Site struct {
	Id   string           `json:"id" xml:"id"`
	Name string           `json:":name" xml:"name"`
	Cfg  SiteConfigObject `json:"config" xml:"config"` /* this probably contains JSON */
}

type SiteConfigObject map[string]interface{}

...

body, err := anyxml.Xml(getSitesResponse, "GetSitesResponse")
```

```Could not marshal object: xml: unsupported type: braunclient.SiteConfigObject```

I think the issue is that SiteConfigObject contains maps, not all top-level objects.  Example:

```
{
  Id: "city",
  Name: "RIT",
  Cfg: {
    category1: {  a: 1, b: 2 },
    category 2: { c: 3, d: 4 }
  }
}
```

The problem is that my objects have an arbitrary element 'Cfg" in them that can contain maps, numbers, or strings in any combination.  I'm looking for a way to XML serialize truly arbitrary objects, not just flat maps.  I'm just trying to figure out if anyxml should be able to do this, or am I doing something wrong.

--C

**Comment by clbanning** [comment]
`anyxml` doesn't import package `braunclient` so it doesn't know type `SiteConfigObject`.  You can coerce it doing something like this - https://go.dev/play/p/jb-K_wYcLZi.

**Comment by wz2b** [comment]
Right, that was just an example of a nested object... bad example on my part.  I meant the type right above.

**Comment by clbanning** [comment]
`SiteConfigObject` is a type that is unknown to `anyxml`. It is defined in the `braunclient` package and is only known to packages that import `braunclient`. That is the error. 

This go playground example shows how you can convert the value so it can be passed successfully to `anyxml` - https://go.dev/play/p/QKlYeD-yX58

**Comment by clbanning** [comment]
https://go.dev/play/p/h6eZI-frfQ7
